import './globals.css';
import type { Metadata } from 'next';
import { Providers } from "@/providers";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ height: "100%" }}>
    <body style={{ height: "100%" }}>
      <main style={{ padding: 40, background: "lightblue", height: "100%" }}>
        <Providers>
          {children}
        </Providers>
      </main>
    </body>
    </html>
  );
}
